language: cpp
before_script:
- sudo apt-get install libboost-test-dev -y
- sudo apt-get install libgtest-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cmake .
- cmake --build .
#- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T Otus2-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uandrewgavluk:$BINTRAY_API_KEY "https://api.bintray.com/content/andrewgavluk/Otus-1/Otus2/$TRAVIS_BUILD_NUMBER/Otus2-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"